<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="VanitasPC" failures="1" tests="3" name="JavaStartSeleniumRozdzial_9.tests.FailedLoginTests" time="6.665" errors="0" timestamp="2022-04-24T17:43:30 CEST" skipped="2">
  <testcase classname="JavaStartSeleniumRozdzial_9.tests.FailedLoginTests" name="asUserTryToLogInWithIncorrectLoginAndPassword" time="1.893">
    <skipped/>
  </testcase> <!-- asUserTryToLogInWithIncorrectLoginAndPassword -->
  <system-out/>
  <testcase classname="JavaStartSeleniumRozdzial_9.tests.FailedLoginTests" name="asUserTryToLogInWithIncorrectLoginAndPassword" time="1.497">
    <failure message="Element text was &lt;Invalid username or password. Signon failed.&gt; expecting to be &lt;Invalid username or password. Signon failed.XXX&gt;!" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Element text was <Invalid username or password. Signon failed.> expecting to be <Invalid username or password. Signon failed.XXX>!
at JavaStartSeleniumRozdzial_9.page.objects.LoginPage.assertThatWarningIsDisplayed(LoginPage.java:63)
at JavaStartSeleniumRozdzial_9.tests.FailedLoginTests.asUserTryToLogInWithIncorrectLoginAndPassword(FailedLoginTests.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:262)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:32)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:467)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
]]>
    </failure>
  </testcase> <!-- asUserTryToLogInWithIncorrectLoginAndPassword -->
  <system-out/>
  <testcase classname="JavaStartSeleniumRozdzial_9.tests.FailedLoginTests" name="asUserTryToLogInWithIncorrectLoginAndPassword" time="3.275">
    <skipped/>
  </testcase> <!-- asUserTryToLogInWithIncorrectLoginAndPassword -->
  <system-out/>
</testsuite> <!-- JavaStartSeleniumRozdzial_9.tests.FailedLoginTests -->
